name: Upload to PyPI
on:
  push:
    tags:
      - "v*"
jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure tag is on develop
        run: |
          git fetch origin develop
          git merge-base --is-ancestor $GITHUB_SHA origin/develop

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install libs
        run: pip install build twine

      - name: Build package
        run: python -m build

      - name: Create ~/.pypirc
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          cat > ~/.pypirc <<EOF
          [pypi]
          username = $PYPI_USERNAME
          password = $PYPI_PASSWORD
          EOF

      - name: Upload to PyPI
        run: twine upload --verbose dist/*

      - name: Remove ~/.pypirc if exists
        if: always()
        run: "[ -f ~/.pypirc ] && rm ~/.pypirc"
